[package]
name = "hoddor"
version = "0.1.0"
authors = ["Gatewatcher Frontend Team <frontend@gatewatcher.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
once_cell = "1.10.0"
wasm-bindgen = "0.2.84"
console_error_panic_hook = { version = "0.1.7", optional = true }
wasm-bindgen-futures = { version = "0.4", features = ["futures-core-03-stream"] }

serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.3"
serde_json = "1.0"

argon2 = "0.5.3"
rand_core = { version = "0.6.4", features = ["std"] }
getrandom = { version = "0.2.15", features = ["js"] }
chacha20poly1305 = "0.10.1"
rand = "0.8.5"

js-sys = "0.3.76"

# --- HMAC + SHA2 for vault integrity ---
hmac = "0.12.1"
sha2 = "0.10.8"

base64 = "0.21.7"
futures-util = "0.3.31"  # Add futures-util crate

[dependencies.web-sys]
version = "0.3.64"
features = [
    "Lock",
    "LockManager",
    "console",
    'Window',
    'Performance',
    'StorageManager',
    'FileSystemDirectoryHandle',
    'FileSystemFileHandle',
    'FileSystemHandle',
    'FileSystemGetFileOptions',
    'FileSystemSyncAccessHandle',
    'WritableStreamDefaultWriter',
    'Blob',
    'File',
    'TextDecoder',
    'WorkerGlobalScope',
    'Window',
    'Navigator',
    'WorkerNavigator',
    'Storage',
    'FileSystemWritableFileStream',
    'WritableStream',
    'LockOptions',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
opt-level = "s"
