name: CI & Release

on:
  push:
    branches:
      - main
      - 66-create-github-actions-to-release-on-gatewatcher-scope

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
          scope: "@gatewatcher"

      - name: Install npm dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # - name: Run semantic-release
      #   uses: cycjimmy/semantic-release-action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
